server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 337a8c1XD
    url: jdbc:mysql://localhost:3306/rental
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        show_sql: true